/**
 * End-to-end DOCX generation example — v1 scope only.
 * Exercises: paragraphs, runs, run properties, paragraph properties,
 *            tables, section properties, styles, core/extended properties.
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  DocxBuilder,
  paragraph,
  textRun,
  pageBreak,
  emptyParagraph,
  ptToTwips,
  ptToHalfPt,
  inToTwips,
} from '../src/index';

async function main() {
  const builder = new DocxBuilder();

  // ---- Document properties ----
  builder.setCoreProperties({
    title:    'ooxmlgen v1 Test Document',
    creator:  'ooxmlgen',
    created:  new Date('2026-04-01T00:00:00Z'),
    modified: new Date('2026-04-01T00:00:00Z'),
  });

  // ---- Page setup: A4, 2.5cm margins ----
  builder.setPageSize({ w: 11906, h: 16838 });
  builder.setPageMargins({
    top:    ptToTwips(56.7),   // ~2cm
    right:  ptToTwips(56.7),
    bottom: ptToTwips(56.7),
    left:   ptToTwips(56.7),
    header: ptToTwips(35.4),
    footer: ptToTwips(35.4),
    gutter: 0,
  });

  // ---- Styles ----
  builder.addStyle({
    type: 'paragraph', styleId: 'Heading1', name: 'heading 1',
    basedOn: 'Normal', next: 'Normal',
    pPr: { outlineLvl: 0, spacing: { before: ptToTwips(12), after: ptToTwips(6) } },
    rPr: { b: true, sz: ptToHalfPt(16), color: { val: '2E74B5' } },
  });
  builder.addStyle({
    type: 'paragraph', styleId: 'Normal', name: 'Normal', default: true,
    pPr: { spacing: { after: ptToTwips(8), line: 276, lineRule: 'auto' } },
    rPr: { sz: ptToHalfPt(11), rFonts: { ascii: 'Calibri', hAnsi: 'Calibri' } },
  });

  // ---- Content ----

  // Heading
  builder.addBlock(paragraph(
    [{ text: 'ooxmlgen v1 — End-to-End Test', rPr: {} }],
    { pStyle: 'Heading1' },
  ));

  // Plain paragraph
  builder.addBlock(paragraph([
    'This document was generated by ',
    { text: 'ooxmlgen', rPr: { b: true } },
    ' using the ECMA-376 5th edition Strict schema.',
  ]));

  // Paragraph with mixed formatting
  builder.addBlock(paragraph([
    { text: 'Bold',      rPr: { b: true } },
    { text: ', ',        rPr: {} },
    { text: 'italic',    rPr: { i: true } },
    { text: ', ',        rPr: {} },
    { text: 'underline', rPr: { u: 'single' } },
    { text: ', ',        rPr: {} },
    { text: 'red text',  rPr: { color: { val: 'FF0000' } } },
    { text: '.',         rPr: {} },
  ]));

  // Paragraph with alignment
  builder.addBlock(paragraph(
    [{ text: 'This paragraph is centered.', rPr: {} }],
    { jc: 'center' },
  ));

  // Paragraph with indentation
  builder.addBlock(paragraph(
    [{ text: 'This paragraph has a first-line indent of 0.5 inches.', rPr: {} }],
    { ind: { firstLine: inToTwips(0.5) } },
  ));

  // Page break
  builder.addBlock(pageBreak());

  // Heading on page 2
  builder.addBlock(paragraph(
    [{ text: 'Table Example', rPr: {} }],
    { pStyle: 'Heading1' },
  ));

  // Table: 3 columns, 3 rows
  const colW = Math.round(11906 / 3);  // equal thirds of page width
  builder.addTable({
    tblPr: {
      tblW: { w: 11906, type: 'dxa' },
      tblBorders: {
        top:     { val: 'single', sz: 4, space: 0, color: '000000' },
        bottom:  { val: 'single', sz: 4, space: 0, color: '000000' },
        start:   { val: 'single', sz: 4, space: 0, color: '000000' },
        end:     { val: 'single', sz: 4, space: 0, color: '000000' },
        insideH: { val: 'single', sz: 4, space: 0, color: '000000' },
        insideV: { val: 'single', sz: 4, space: 0, color: '000000' },
      },
    },
    colWidths: [colW, colW, colW],
    rows: [
      // Header row
      {
        cells: [
          { content: [paragraph([{ text: 'Column A', rPr: { b: true } }])] },
          { content: [paragraph([{ text: 'Column B', rPr: { b: true } }])] },
          { content: [paragraph([{ text: 'Column C', rPr: { b: true } }])] },
        ],
      },
      // Data row 1
      {
        cells: [
          { content: [paragraph(['Alpha'])] },
          { content: [paragraph(['Beta'])] },
          { content: [paragraph(['Gamma'])] },
        ],
      },
      // Data row 2
      {
        cells: [
          { content: [paragraph(['1'])] },
          { content: [paragraph(['2'])] },
          { content: [paragraph(['3'])] },
        ],
      },
    ],
  });

  // Trailing paragraph (required after table for valid DOCX)
  builder.addBlock(emptyParagraph());

  // ---- Build ----
  const buffer = await builder.build();
  const outPath = path.join(__dirname, 'output.docx');
  fs.writeFileSync(outPath, buffer);
  console.log(`Written: ${outPath} (${buffer.length} bytes)`);
}

main().catch(err => { console.error(err); process.exit(1); });
