/**
 * Batch 4 helpers — caption paragraphs, TOC paragraphs
 *
 * These are separated from fields.ts to avoid circular dependencies.
 */

import type { WmlParagraph, WmlRunProperties, WmlParagraphProperties } from './types';
import { tocField, seqField } from './fields';

// ---------------------------------------------------------------------------
// Caption helper
// ---------------------------------------------------------------------------

/**
 * Create a caption paragraph with a SEQ field prefix.
 * Reusable for figures, tables, equations, etc.
 *
 * @param label - Caption label, e.g. "Figure", "Table"
 * @param captionText - The caption description text
 * @param options - Optional formatting and numbering options
 * @param paragraphFactory - Factory function to create paragraphs
 * @returns A WmlParagraph with the caption content
 *
 * @example
 * // "Figure 1: System architecture diagram"
 * const caption = captionParagraph('Figure', 'System architecture diagram');
 * builder.addBlock(caption);
 */
export function createCaptionParagraph(
  label: string,
  captionText: string,
  options: {
    pStyle?: string;
    pPr?: WmlParagraphProperties;
    rPr?: WmlRunProperties;
    seqOptions?: Parameters<typeof seqField>[1];
  } = {},
  paragraphFactory: (runs: any[], pPr?: WmlParagraphProperties) => WmlParagraph,
): WmlParagraph {
  const seqRuns = seqField(label, {
    displayText: '1',
    ...options.seqOptions,
    rPr: options.rPr,
  });

  const runs = [
    { text: `${label} `, rPr: options.rPr },
    ...seqRuns,
    { text: `: ${captionText}`, rPr: options.rPr },
  ];

  return paragraphFactory(runs, {
    ...options.pPr,
    ...(options.pStyle ? { pStyle: options.pStyle } : {}),
  });
}

/**
 * Create a TOC placeholder paragraph.
 * The actual TOC is generated by Word when updateFields is true in settings.
 *
 * @param options - TOC configuration
 * @param paragraphFactory - Factory function to create paragraphs
 * @returns A WmlParagraph containing the TOC field
 *
 * @example
 * builder.addBlock(tableOfContents({ headingLevels: [1, 2, 3] }));
 */
export function createTableOfContents(
  options: {
    headingLevels?: number[];
    customSwitches?: string;
    pStyle?: string;
    pPr?: WmlParagraphProperties;
    rPr?: WmlRunProperties;
  } = {},
  paragraphFactory: (runs: any[], pPr?: WmlParagraphProperties) => WmlParagraph,
): WmlParagraph {
  const tocRuns = tocField({
    headingLevels: options.headingLevels,
    customSwitches: options.customSwitches,
    withHyperlinks: true,
    withPageNumbers: true,
    displayText: 'Click here to update the table of contents.',
    rPr: options.rPr,
  });

  return paragraphFactory(tocRuns, {
    ...options.pPr,
    ...(options.pStyle ? { pStyle: options.pStyle } : {}),
  });
}